# Form implementation generated from reading ui file 'interviews_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormInterviews(object):
    def setupUi(self, FormInterviews):
        FormInterviews.setObjectName("FormInterviews")
        FormInterviews.resize(750, 590)
        FormInterviews.setMinimumSize(QtCore.QSize(750, 590))
        FormInterviews.setMaximumSize(QtCore.QSize(750, 590))
        FormInterviews.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.499773, y1:1, x2:0.5, y2:0.00568182, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.labelPicture = QtWidgets.QLabel(parent=FormInterviews)
        self.labelPicture.setGeometry(QtCore.QRect(10, 10, 201, 171))
        self.labelPicture.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelPicture.setText("")
        self.labelPicture.setPixmap(QtGui.QPixmap("pictures/interviews_menu.png"))
        self.labelPicture.setScaledContents(True)
        self.labelPicture.setObjectName("labelPicture")
        self.labelLogo = QtWidgets.QLabel(parent=FormInterviews)
        self.labelLogo.setGeometry(QtCore.QRect(210, 12, 261, 101))
        self.labelLogo.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("pictures/wehere_logo.ico"))
        self.labelLogo.setObjectName("labelLogo")
        self.labelInterviews = QtWidgets.QLabel(parent=FormInterviews)
        self.labelInterviews.setGeometry(QtCore.QRect(470, 40, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        self.labelInterviews.setFont(font)
        self.labelInterviews.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"color: rgb(71, 84, 88);")
        self.labelInterviews.setObjectName("labelInterviews")
        self.pushButtonExit = QtWidgets.QPushButton(parent=FormInterviews)
        self.pushButtonExit.setGeometry(QtCore.QRect(20, 530, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonPreferences = QtWidgets.QPushButton(parent=FormInterviews)
        self.pushButtonPreferences.setGeometry(QtCore.QRect(20, 460, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonPreferences.setFont(font)
        self.pushButtonPreferences.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}")
        self.pushButtonPreferences.setObjectName("pushButtonPreferences")
        self.pushButtonSubmittedProjects = QtWidgets.QPushButton(parent=FormInterviews)
        self.pushButtonSubmittedProjects.setGeometry(QtCore.QRect(20, 320, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonSubmittedProjects.setFont(font)
        self.pushButtonSubmittedProjects.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}")
        self.pushButtonSubmittedProjects.setObjectName("pushButtonSubmittedProjects")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=FormInterviews)
        self.lineEditUsername.setEnabled(True)
        self.lineEditUsername.setGeometry(QtCore.QRect(20, 200, 171, 31))
        self.lineEditUsername.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEditUsername.setStyleSheet("QLineEdit {\n"
"  border: 2px solid rgb(38, 38, 48);\n"
"  border-radius: 15px;\n"
"  color: #FFF;\n"
"  padding-left: 15px;\n"
"  background-color: rgb(36, 36, 36);\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"\n"
" QLineEdit:focus  {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"  background-color: rgb(47, 47, 47);\n"
"}\n"
"\n"
"   \n"
"\n"
"\n"
"\n"
"")
        self.lineEditUsername.setText("")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.tableWidget = QtWidgets.QTableWidget(parent=FormInterviews)
        self.tableWidget.setGeometry(QtCore.QRect(210, 200, 511, 361))
        self.tableWidget.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(170)
        self.pushButtonSearch = QtWidgets.QPushButton(parent=FormInterviews)
        self.pushButtonSearch.setGeometry(QtCore.QRect(20, 250, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonSearch.setFont(font)
        self.pushButtonSearch.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}")
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.labelMenu = QtWidgets.QLabel(parent=FormInterviews)
        self.labelMenu.setGeometry(QtCore.QRect(420, 90, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        self.labelMenu.setFont(font)
        self.labelMenu.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"color: rgb(71, 84, 88);")
        self.labelMenu.setObjectName("labelMenu")
        self.pushButtonProjectArrivals = QtWidgets.QPushButton(parent=FormInterviews)
        self.pushButtonProjectArrivals.setGeometry(QtCore.QRect(20, 390, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.pushButtonProjectArrivals.setFont(font)
        self.pushButtonProjectArrivals.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"}")
        self.pushButtonProjectArrivals.setObjectName("pushButtonProjectArrivals")

        self.retranslateUi(FormInterviews)
        QtCore.QMetaObject.connectSlotsByName(FormInterviews)

    def retranslateUi(self, FormInterviews):
        _translate = QtCore.QCoreApplication.translate
        FormInterviews.setWindowTitle(_translate("FormInterviews", "INTERVIEWS"))
        self.labelInterviews.setText(_translate("FormInterviews", "INTERVIEWS "))
        self.pushButtonExit.setText(_translate("FormInterviews", "Exit"))
        self.pushButtonPreferences.setText(_translate("FormInterviews", "Preferences"))
        self.pushButtonSubmittedProjects.setText(_translate("FormInterviews", "Submitted Projects"))
        self.lineEditUsername.setPlaceholderText(_translate("FormInterviews", "      Name or Surname"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormInterviews", "Name Surname"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormInterviews", "Project \n"
"Submission Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormInterviews", "Project \n"
"Arrival Date"))
        self.pushButtonSearch.setText(_translate("FormInterviews", "Search"))
        self.labelMenu.setText(_translate("FormInterviews", "MENU"))
        self.pushButtonProjectArrivals.setText(_translate("FormInterviews", "Project Arrivals"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormInterviews = QtWidgets.QWidget()
    ui = Ui_FormInterviews()
    ui.setupUi(FormInterviews)
    FormInterviews.show()
    sys.exit(app.exec())
