# Form implementation generated from reading ui file 'user_menu_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pictures/werhere_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.499773, y1:1, x2:0.5, y2:0.00568182, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.labelLogo = QtWidgets.QLabel(parent=Form)
        self.labelLogo.setGeometry(QtCore.QRect(120, 20, 261, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.labelLogo.setFont(font)
        self.labelLogo.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("pictures/wehere_logo.ico"))
        self.labelLogo.setObjectName("labelLogo")
        self.labelPicMenu = QtWidgets.QLabel(parent=Form)
        self.labelPicMenu.setGeometry(QtCore.QRect(80, 130, 341, 311))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.labelPicMenu.setFont(font)
        self.labelPicMenu.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelPicMenu.setText("")
        self.labelPicMenu.setPixmap(QtGui.QPixmap("pictures/user_loop.png"))
        self.labelPicMenu.setScaledContents(True)
        self.labelPicMenu.setObjectName("labelPicMenu")
        self.pushButtonApplications = QtWidgets.QPushButton(parent=Form)
        self.pushButtonApplications.setGeometry(QtCore.QRect(213, 155, 75, 75))
        self.pushButtonApplications.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButtonApplications.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonApplications.setFont(font)
        self.pushButtonApplications.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    \n"
"    background-color: rgb(0, 204, 209);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(0, 251, 255);\n"
"}\n"
"")
        self.pushButtonApplications.setObjectName("pushButtonApplications")
        self.pushButtonInterviews = QtWidgets.QPushButton(parent=Form)
        self.pushButtonInterviews.setGeometry(QtCore.QRect(318, 223, 75, 75))
        self.pushButtonInterviews.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButtonInterviews.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonInterviews.setFont(font)
        self.pushButtonInterviews.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(0, 108, 143);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 196, 255);\n"
"}\n"
"")
        self.pushButtonInterviews.setObjectName("pushButtonInterviews")
        self.pushButtonExit = QtWidgets.QPushButton(parent=Form)
        self.pushButtonExit.setGeometry(QtCore.QRect(278, 341, 75, 75))
        self.pushButtonExit.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(243, 199, 65);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(162, 132, 43);\n"
"}\n"
"")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonSignOut = QtWidgets.QPushButton(parent=Form)
        self.pushButtonSignOut.setGeometry(QtCore.QRect(149, 341, 75, 75))
        self.pushButtonSignOut.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButtonSignOut.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonSignOut.setFont(font)
        self.pushButtonSignOut.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(255, 140, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(170, 92, 41);\n"
"}\n"
"")
        self.pushButtonSignOut.setObjectName("pushButtonSignOut")
        self.pushButtonMentorMeeting = QtWidgets.QPushButton(parent=Form)
        self.pushButtonMentorMeeting.setGeometry(QtCore.QRect(107, 224, 75, 75))
        self.pushButtonMentorMeeting.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButtonMentorMeeting.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonMentorMeeting.setFont(font)
        self.pushButtonMentorMeeting.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(255, 109, 102);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(173, 73, 69);\n"
"}\n"
"")
        self.pushButtonMentorMeeting.setObjectName("pushButtonMentorMeeting")
        self.labelUsers = QtWidgets.QLabel(parent=Form)
        self.labelUsers.setGeometry(QtCore.QRect(200, 245, 100, 100))
        self.labelUsers.setMinimumSize(QtCore.QSize(100, 100))
        self.labelUsers.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.labelUsers.setFont(font)
        self.labelUsers.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelUsers.setText("")
        self.labelUsers.setPixmap(QtGui.QPixmap("pictures/user_icon.png"))
        self.labelUsers.setScaledContents(True)
        self.labelUsers.setObjectName("labelUsers")
        self.frameCurrentUser = QtWidgets.QFrame(parent=Form)
        self.frameCurrentUser.setGeometry(QtCore.QRect(430, 0, 71, 51))
        self.frameCurrentUser.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.frameCurrentUser.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCurrentUser.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCurrentUser.setObjectName("frameCurrentUser")
        self.labelCurrentUser = QtWidgets.QLabel(parent=self.frameCurrentUser)
        self.labelCurrentUser.setGeometry(QtCore.QRect(20, 0, 31, 31))
        self.labelCurrentUser.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.labelCurrentUser.setPixmap(QtGui.QPixmap("pictures/wehere_icon.png"))
        self.labelCurrentUser.setObjectName("labelCurrentUser")
        self.labelAccountName = QtWidgets.QLabel(parent=self.frameCurrentUser)
        self.labelAccountName.setGeometry(QtCore.QRect(10, 30, 51, 20))
        self.labelAccountName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelAccountName.setObjectName("labelAccountName")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButtonExit, self.pushButtonSignOut)
        Form.setTabOrder(self.pushButtonSignOut, self.pushButtonMentorMeeting)
        Form.setTabOrder(self.pushButtonMentorMeeting, self.pushButtonApplications)
        Form.setTabOrder(self.pushButtonApplications, self.pushButtonInterviews)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "USER MENU"))
        self.pushButtonApplications.setText(_translate("Form", "Applications"))
        self.pushButtonInterviews.setText(_translate("Form", "Interviews"))
        self.pushButtonExit.setText(_translate("Form", "Exit"))
        self.pushButtonSignOut.setText(_translate("Form", "Sign Out"))
        self.pushButtonMentorMeeting.setText(_translate("Form", "Mentor\n"
"Meeting"))
        self.labelAccountName.setText(_translate("Form", "Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
