# Form implementation generated from reading ui file 'UI_Files/settings_ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormSettings(object):
    def setupUi(self, FormSettings):
        FormSettings.setObjectName("FormSettings")
        FormSettings.resize(301, 544)
        FormSettings.setMinimumSize(QtCore.QSize(301, 544))
        FormSettings.setMaximumSize(QtCore.QSize(301, 544))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\pictures/werhere_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FormSettings.setWindowIcon(icon)
        FormSettings.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0.472, y1:0, x2:0.472, y2:1, stop:0.0795455 rgba(24, 125, 151, 255), stop:1 rgba(255, 255, 255, 255));")
        self.labelPicture = QtWidgets.QLabel(parent=FormSettings)
        self.labelPicture.setGeometry(QtCore.QRect(20, 20, 281, 201))
        self.labelPicture.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelPicture.setText("")
        self.labelPicture.setPixmap(QtGui.QPixmap("UI_Files\\pictures/settingFoto.png"))
        self.labelPicture.setObjectName("labelPicture")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=FormSettings)
        self.lineEditUserName.setEnabled(False)
        self.lineEditUserName.setGeometry(QtCore.QRect(60, 270, 191, 31))
        self.lineEditUserName.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
" color: rgb(5, 58, 85);\n"
"  border: 2px solid rgba(38, 38, 48,20);\n"
"  border-radius: 15px;\n"
"  \n"
"  padding-left: 15px;\n"
"  background-color: rgba(36, 36, 36,0);\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"\n"
" QLineEdit:focus  {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"\n"
"}\n"
"\n"
"   \n"
"\n"
"\n"
"\n"
"")
        self.lineEditUserName.setText("")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditName = QtWidgets.QLineEdit(parent=FormSettings)
        self.lineEditName.setEnabled(False)
        self.lineEditName.setGeometry(QtCore.QRect(60, 310, 191, 31))
        self.lineEditName.setStyleSheet("QLineEdit {\n"
" color: rgb(5, 58, 85);\n"
"  border: 2px solid rgba(38, 38, 48,20);\n"
"  border-radius: 15px;\n"
"  padding-left: 15px;\n"
"  background-color: rgba(36, 36, 36,0);\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"\n"
" QLineEdit:focus  {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"\n"
"}\n"
"\n"
"   \n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lineEditName.setText("")
        self.lineEditName.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditSurname = QtWidgets.QLineEdit(parent=FormSettings)
        self.lineEditSurname.setEnabled(False)
        self.lineEditSurname.setGeometry(QtCore.QRect(60, 350, 191, 31))
        self.lineEditSurname.setStyleSheet("QLineEdit {\n"
" color: rgb(5, 58, 85);\n"
"  border: 2px solid rgba(38, 38, 48,20);\n"
"  border-radius: 15px;\n"
"  padding-left: 15px;\n"
"  background-color: rgba(36, 36, 36,0);\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"\n"
" QLineEdit:focus  {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"\n"
"}\n"
"\n"
"   \n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lineEditSurname.setText("")
        self.lineEditSurname.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditSurname.setObjectName("lineEditSurname")
        self.lineEditAccountType = QtWidgets.QLineEdit(parent=FormSettings)
        self.lineEditAccountType.setEnabled(False)
        self.lineEditAccountType.setGeometry(QtCore.QRect(60, 390, 191, 31))
        self.lineEditAccountType.setStyleSheet("QLineEdit {\n"
" color: rgb(5, 58, 85);\n"
"  border: 2px solid rgba(38, 38, 48,20);\n"
"  border-radius: 15px;\n"
"  padding-left: 15px;\n"
"  background-color: rgba(36, 36, 36,0);\n"
" \n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(0, 255, 255);\n"
"}\n"
"\n"
" QLineEdit:focus  {\n"
"  border: 2px solid rgb(35, 218, 233);\n"
"\n"
"}\n"
"\n"
"   \n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lineEditAccountType.setText("")
        self.lineEditAccountType.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditAccountType.setObjectName("lineEditAccountType")
        self.labelWellcome = QtWidgets.QLabel(parent=FormSettings)
        self.labelWellcome.setGeometry(QtCore.QRect(45, 240, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(20)
        self.labelWellcome.setFont(font)
        self.labelWellcome.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelWellcome.setText("")
        self.labelWellcome.setObjectName("labelWellcome")
        self.frameButtons = QtWidgets.QFrame(parent=FormSettings)
        self.frameButtons.setGeometry(QtCore.QRect(50, 430, 211, 91))
        self.frameButtons.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frameButtons.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.pushButtonChangePassword = QtWidgets.QPushButton(parent=self.frameButtons)
        self.pushButtonChangePassword.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.pushButtonChangePassword.setMouseTracking(True)
        self.pushButtonChangePassword.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButtonChangePassword.setStyleSheet("\n"
"QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
" \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(162, 0, 0);\n"
"    \n"
"}\n"
"\n"
"")
        self.pushButtonChangePassword.setObjectName("pushButtonChangePassword")
        self.pushButtonChangeAccountDetails = QtWidgets.QPushButton(parent=self.frameButtons)
        self.pushButtonChangeAccountDetails.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.pushButtonChangeAccountDetails.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(162, 0, 0);\n"
"}\n"
"")
        self.pushButtonChangeAccountDetails.setObjectName("pushButtonChangeAccountDetails")
        self.pushButtonApprove = QtWidgets.QPushButton(parent=FormSettings)
        self.pushButtonApprove.setGeometry(QtCore.QRect(60, 440, 191, 31))
        self.pushButtonApprove.setMouseTracking(True)
        self.pushButtonApprove.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.pushButtonApprove.setStyleSheet("\n"
"QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
" \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(162, 0, 0);\n"
"    \n"
"}\n"
"\n"
"")
        self.pushButtonApprove.setObjectName("pushButtonApprove")
        self.pushButtonCancel = QtWidgets.QPushButton(parent=FormSettings)
        self.pushButtonCancel.setGeometry(QtCore.QRect(60, 480, 191, 31))
        self.pushButtonCancel.setStyleSheet("QPushButton{\n"
"    border-radius : 15px;\n"
"    background-color : rgb(25, 200, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(20, 135, 135);\n"
"    border: 2px solid rgb(162, 0, 0);\n"
"}\n"
"")
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.pushButtonCancel.raise_()
        self.pushButtonApprove.raise_()
        self.labelPicture.raise_()
        self.lineEditUserName.raise_()
        self.lineEditName.raise_()
        self.lineEditSurname.raise_()
        self.lineEditAccountType.raise_()
        self.labelWellcome.raise_()
        self.frameButtons.raise_()

        self.retranslateUi(FormSettings)
        QtCore.QMetaObject.connectSlotsByName(FormSettings)

    def retranslateUi(self, FormSettings):
        _translate = QtCore.QCoreApplication.translate
        FormSettings.setWindowTitle(_translate("FormSettings", "Settings"))
        self.lineEditUserName.setPlaceholderText(_translate("FormSettings", "Username"))
        self.lineEditName.setPlaceholderText(_translate("FormSettings", "Name"))
        self.lineEditSurname.setPlaceholderText(_translate("FormSettings", "Surname"))
        self.lineEditAccountType.setPlaceholderText(_translate("FormSettings", "Account Type"))
        self.pushButtonChangePassword.setText(_translate("FormSettings", "Change Password"))
        self.pushButtonChangeAccountDetails.setText(_translate("FormSettings", "Edit Account Details"))
        self.pushButtonApprove.setText(_translate("FormSettings", "APPROVE"))
        self.pushButtonCancel.setText(_translate("FormSettings", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSettings = QtWidgets.QWidget()
    ui = Ui_FormSettings()
    ui.setupUi(FormSettings)
    FormSettings.show()
    sys.exit(app.exec())
