# Form implementation generated from reading ui file 'UI_Files/user_menu_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormUserMenu(object):
    def setupUi(self, FormUserMenu):
        FormUserMenu.setObjectName("FormUserMenu")
        FormUserMenu.resize(500, 500)
        FormUserMenu.setMinimumSize(QtCore.QSize(500, 500))
        FormUserMenu.setMaximumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\pictures/werhere_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FormUserMenu.setWindowIcon(icon)
        FormUserMenu.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.499773, y1:1, x2:0.5, y2:0.00568182, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.labelLogo = QtWidgets.QLabel(parent=FormUserMenu)
        self.labelLogo.setGeometry(QtCore.QRect(120, 20, 261, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.labelLogo.setFont(font)
        self.labelLogo.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("UI_Files\\pictures/werhere_logo.ico"))
        self.labelLogo.setObjectName("labelLogo")
        self.labelPicMenu = QtWidgets.QLabel(parent=FormUserMenu)
        self.labelPicMenu.setGeometry(QtCore.QRect(80, 130, 341, 311))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.labelPicMenu.setFont(font)
        self.labelPicMenu.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelPicMenu.setText("")
        self.labelPicMenu.setPixmap(QtGui.QPixmap("UI_Files\\pictures/user_loop.png"))
        self.labelPicMenu.setScaledContents(True)
        self.labelPicMenu.setObjectName("labelPicMenu")
        self.pushButtonApplications = QtWidgets.QPushButton(parent=FormUserMenu)
        self.pushButtonApplications.setGeometry(QtCore.QRect(213, 155, 75, 75))
        self.pushButtonApplications.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButtonApplications.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonApplications.setFont(font)
        self.pushButtonApplications.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    \n"
"    background-color: rgb(0, 204, 209);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(0, 251, 255);\n"
"}\n"
"")
        self.pushButtonApplications.setObjectName("pushButtonApplications")
        self.pushButtonInterviews = QtWidgets.QPushButton(parent=FormUserMenu)
        self.pushButtonInterviews.setGeometry(QtCore.QRect(318, 223, 75, 75))
        self.pushButtonInterviews.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButtonInterviews.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonInterviews.setFont(font)
        self.pushButtonInterviews.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(0, 108, 143);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 196, 255);\n"
"}\n"
"")
        self.pushButtonInterviews.setObjectName("pushButtonInterviews")
        self.pushButtonExit = QtWidgets.QPushButton(parent=FormUserMenu)
        self.pushButtonExit.setGeometry(QtCore.QRect(278, 341, 75, 75))
        self.pushButtonExit.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(243, 199, 65);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(162, 132, 43);\n"
"}\n"
"")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonSignOut = QtWidgets.QPushButton(parent=FormUserMenu)
        self.pushButtonSignOut.setGeometry(QtCore.QRect(149, 341, 75, 75))
        self.pushButtonSignOut.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButtonSignOut.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonSignOut.setFont(font)
        self.pushButtonSignOut.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(255, 140, 61);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(170, 92, 41);\n"
"}\n"
"")
        self.pushButtonSignOut.setObjectName("pushButtonSignOut")
        self.pushButtonMentorMeeting = QtWidgets.QPushButton(parent=FormUserMenu)
        self.pushButtonMentorMeeting.setGeometry(QtCore.QRect(107, 224, 75, 75))
        self.pushButtonMentorMeeting.setMinimumSize(QtCore.QSize(75, 75))
        self.pushButtonMentorMeeting.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonMentorMeeting.setFont(font)
        self.pushButtonMentorMeeting.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: rgb(255, 109, 102);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(173, 73, 69);\n"
"}\n"
"")
        self.pushButtonMentorMeeting.setObjectName("pushButtonMentorMeeting")
        self.labelUsers = QtWidgets.QLabel(parent=FormUserMenu)
        self.labelUsers.setGeometry(QtCore.QRect(200, 245, 100, 100))
        self.labelUsers.setMinimumSize(QtCore.QSize(100, 100))
        self.labelUsers.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.labelUsers.setFont(font)
        self.labelUsers.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.labelUsers.setText("")
        self.labelUsers.setPixmap(QtGui.QPixmap("UI_Files\\pictures/user_icon.png"))
        self.labelUsers.setScaledContents(True)
        self.labelUsers.setObjectName("labelUsers")
        self.frameCurrentUser = QtWidgets.QFrame(parent=FormUserMenu)
        self.frameCurrentUser.setGeometry(QtCore.QRect(430, 0, 71, 51))
        self.frameCurrentUser.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.frameCurrentUser.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameCurrentUser.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameCurrentUser.setObjectName("frameCurrentUser")
        self.labelCurrentUserPic = QtWidgets.QLabel(parent=self.frameCurrentUser)
        self.labelCurrentUserPic.setGeometry(QtCore.QRect(20, 0, 31, 31))
        self.labelCurrentUserPic.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.labelCurrentUserPic.setPixmap(QtGui.QPixmap("UI_Files\\pictures/werhere_icon.png"))
        self.labelCurrentUserPic.setObjectName("labelCurrentUserPic")
        self.labelCurrentUser = QtWidgets.QLabel(parent=self.frameCurrentUser)
        self.labelCurrentUser.setGeometry(QtCore.QRect(10, 30, 51, 20))
        self.labelCurrentUser.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCurrentUser.setObjectName("labelCurrentUser")
        self.toolButtonAccount = QtWidgets.QToolButton(parent=self.frameCurrentUser)
        self.toolButtonAccount.setGeometry(QtCore.QRect(20, 0, 31, 41))
        self.toolButtonAccount.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image:/src_/werhere_icon.png;")
        self.toolButtonAccount.setText("")
        self.toolButtonAccount.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonFollowStyle)
        self.toolButtonAccount.setObjectName("toolButtonAccount")
        self.pushButtonManagement = QtWidgets.QPushButton(parent=FormUserMenu)
        self.pushButtonManagement.setGeometry(QtCore.QRect(210, 250, 81, 81))
        self.pushButtonManagement.setMinimumSize(QtCore.QSize(81, 81))
        self.pushButtonManagement.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        self.pushButtonManagement.setFont(font)
        self.pushButtonManagement.setStyleSheet("QPushButton{\n"
"    border-radius : 37px;\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 123, 0, 255), stop:1 rgba(0, 255, 255, 255));\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 170, 28);\n"
"}\n"
"")
        self.pushButtonManagement.setObjectName("pushButtonManagement")
        self.labelPicMenu.raise_()
        self.labelUsers.raise_()
        self.pushButtonManagement.raise_()
        self.labelLogo.raise_()
        self.pushButtonApplications.raise_()
        self.pushButtonInterviews.raise_()
        self.pushButtonExit.raise_()
        self.pushButtonSignOut.raise_()
        self.pushButtonMentorMeeting.raise_()
        self.frameCurrentUser.raise_()

        self.retranslateUi(FormUserMenu)
        QtCore.QMetaObject.connectSlotsByName(FormUserMenu)
        FormUserMenu.setTabOrder(self.pushButtonExit, self.pushButtonSignOut)
        FormUserMenu.setTabOrder(self.pushButtonSignOut, self.pushButtonMentorMeeting)
        FormUserMenu.setTabOrder(self.pushButtonMentorMeeting, self.pushButtonApplications)
        FormUserMenu.setTabOrder(self.pushButtonApplications, self.pushButtonInterviews)

    def retranslateUi(self, FormUserMenu):
        _translate = QtCore.QCoreApplication.translate
        FormUserMenu.setWindowTitle(_translate("FormUserMenu", "USER MENU"))
        self.pushButtonApplications.setText(_translate("FormUserMenu", "Applications"))
        self.pushButtonInterviews.setText(_translate("FormUserMenu", "Interviews"))
        self.pushButtonExit.setText(_translate("FormUserMenu", "Exit"))
        self.pushButtonSignOut.setText(_translate("FormUserMenu", "Sign Out"))
        self.pushButtonMentorMeeting.setText(_translate("FormUserMenu", "Mentor\n"
"Meeting"))
        self.labelCurrentUser.setText(_translate("FormUserMenu", "Account"))
        self.pushButtonManagement.setText(_translate("FormUserMenu", "Management"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormUserMenu = QtWidgets.QWidget()
    ui = Ui_FormUserMenu()
    ui.setupUi(FormUserMenu)
    FormUserMenu.show()
    sys.exit(app.exec())
