@startuml

skinparam class {
    BackgroundColor LightSkyBlue
}

skinparam classBorder {
    Color red
}

skinparam arrowColor red

package "PyQt6.QtWidgets" {
    class "QWidget" {
        + __init__()
    }

    class "QApplication" {
        + __init__([])
        + exec()
    }
}

package "main" {
    class "connection_hub" {
        + __init__(credentials: str, table: str)
    }

    class "write2table" {
        + __init__(page: QWidget, a_list: list)
    }
}

package "UI_Files" {
    class "interviews_ui" {
        + Ui_FormInterviews()
    }
}

class "InterviewsPage" {
    - current_user: list
    - form_interviews: Ui_FormInterviews
    - interviews: list
    - menu_admin: AdminMenuPage
    - menu_user: UserMenuPage
    + __init__(current_user: list)
    + search_name()
    + get_submitted_projects()
    + get_projects_arrivals()
    + back_menu()
    + app_exit()
}

InterviewsPage --> QWidget
InterviewsPage --> Ui_FormInterviews
InterviewsPage --> UserMenuPage
InterviewsPage --> AdminMenuPage
InterviewsPage --> connection_hub
InterviewsPage --> write2table

InterviewsPage ..> QApplication

@enduml
