@startuml

skinparam class {
    BackgroundColor LightSkyBlue
}

skinparam classBorder {
    Color red
}

skinparam arrowColor red

package "PyQt6.QtWidgets" {
    class "QWidget" {
        + __init__()
    }

    class "QApplication" {
        + __init__([])
        + exec()
    }
}

package "UI_Files" {
    class "user_menu_ui" {
        + Ui_FormUserMenu()
    }
}

package "settings" {
    class "SettingsPage" {
        + __init__(current_user: list)
    }
}

package "mentors" {
    class "MentorPage" {
        + __init__(current_user: list)
    }
}

package "applications" {
    class "ApplicationsPage" {
        + __init__(current_user: list)
    }
}

package "interviews" {
    class "InterviewsPage" {
        + __init__(current_user: list)
    }
}

class "UserMenuPage" {
    - current_user: list
    - user_menu_form: Ui_FormUserMenu
    - settings_window_open: SettingsPage
    - login_window: LoginPage
    - applications_window_open: ApplicationsPage
    - interviews_window_open: InterviewsPage
    - mentor_menu_open: MentorPage
    + __init__()
    + go_settings_page()
    + go_mentors_page()
    + go_applications_page()
    + go_interviews_page()
    + goback_login_page()
    + app_exit()
}

UserMenuPage --> QWidget
UserMenuPage --> Ui_FormUserMenu
UserMenuPage --> SettingsPage
UserMenuPage --> MentorPage
UserMenuPage --> ApplicationsPage
UserMenuPage --> InterviewsPage
UserMenuPage --> LoginPage

UserMenuPage ..> QApplication

@enduml
